### ISSUE TITLE
PCB Silk screen

### ISSUE THREAD

**Issue by finn28** [TOILmodular/Plaits#2]
First I Soldered all the Components and the LEDs didnt work.

I found out, that the Silk Screen is wrong.
Next to the LED IC the Capacitor must be on the Bottom and not on the top.

![WhatsApp Image 2023-06-06 at 14 37 53](https://github.com/TOILmodular/Plaits/assets/32451854/411c9192-adb2-4d61-b8e3-48daeb922a59)

**Comment by finn28** [comment]
Now i saw the closed issue. 
Would be nice to fix it for other people, or write something in the readme.

Best Regards
Finn

**Comment by TOILmodular** [comment]
Thanks for the feedback, Finn. I added the information to the readme. Hope it is clear enough. Let me know, if not.

**Comment by finn28** [comment]
Yes. Thank you :)
