### ISSUE TITLE
EasyEDA files

### ISSUE THREAD

**Issue by Biondilbiondo** [TOILmodular/Plaits#3]
Hi, I would like to order the pre-assembled board from jlcpb, but in order to do that I need either a jlcpcb compliant bom or the easyeda files. It would be great if you can provide one of those (:

**Comment by TOILmodular** [comment]
I am sorry, Biondilbiondo. I fear, I cannot help you with that. I use EasyEDA purely for my PCB design. I even create my own footprints, when needed. I do not check for or use the available components. And I never used that pre-assembly service. The EasyEDA files would not work for that.
My projects are all really for doing the populating yourself.
I hope that will not hinder you from trying.
I had many concerns about hand-soldering the components myself. But in my experience it was not that hard. And you will improve quickly, the more you try.
Some people use cheap SMD learning sets, where you can try out different components and sizes.
I did not even do that.
